export interface TopicList {
  id: string
  name: string
  subject: string
  description: string
  topics: string[]
}

export const CURATED_TOPICS: TopicList[] = [
  {
    id: 'planets-celestial-bodies',
    name: 'Planets & Celestial Bodies',
    subject: 'Science',
    description:
      'Have students debate which planet or celestial body is the most fascinating in our solar system.',
    topics: [
      'Mercury',
      'Venus',
      'Earth',
      'Mars',
      'Jupiter',
      'Saturn',
      'Uranus',
      'Neptune',
      'Pluto',
      'Moon',
      'Titan',
      'Europa',
      'Ganymede',
      'Ceres',
      'Io',
      'Callisto',
    ],
  },
  {
    id: 'us-presidents',
    name: 'U.S. Presidents',
    subject: 'History',
    description:
      'Let students rank the most impactful U.S. presidents through bracket-style elimination.',
    topics: [
      'Washington',
      'Jefferson',
      'Lincoln',
      'T. Roosevelt',
      'FDR',
      'JFK',
      'Reagan',
      'Obama',
      'Adams',
      'Jackson',
      'Grant',
      'Wilson',
      'Truman',
      'Eisenhower',
      'LBJ',
      'Clinton',
    ],
  },
  {
    id: 'shakespeare-plays',
    name: 'Shakespeare Plays',
    subject: 'Literature',
    description:
      'Challenge students to determine the greatest Shakespeare play through class-wide voting rounds.',
    topics: [
      'Hamlet',
      'Macbeth',
      'Romeo and Juliet',
      'A Midsummer Night\'s Dream',
      'Othello',
      'King Lear',
      'The Tempest',
      'Twelfth Night',
      'Julius Caesar',
      'Much Ado About Nothing',
      'The Merchant of Venice',
      'As You Like It',
      'Richard III',
      'Henry V',
      'The Taming of the Shrew',
      'The Winter\'s Tale',
    ],
  },
  {
    id: 'greatest-inventions',
    name: 'Greatest Inventions',
    subject: 'Science',
    description:
      'Spark discussion about which invention had the greatest impact on human civilization.',
    topics: [
      'Printing Press',
      'Electricity',
      'Internet',
      'Telephone',
      'Wheel',
      'Penicillin',
      'Steam Engine',
      'Lightbulb',
      'Automobile',
      'Airplane',
      'Television',
      'Computer',
      'Vaccines',
      'Radio',
      'Compass',
      'Telescope',
    ],
  },
  {
    id: 'ancient-civilizations',
    name: 'Ancient Civilizations',
    subject: 'History',
    description:
      'Have students evaluate which ancient civilization made the most lasting contributions to the world.',
    topics: [
      'Egypt',
      'Rome',
      'Greece',
      'Mesopotamia',
      'China',
      'Indus Valley',
      'Maya',
      'Aztec',
      'Inca',
      'Persia',
      'Carthage',
      'Phoenicia',
      'Mongol Empire',
      'Ottoman Empire',
      'Byzantine Empire',
      'Viking',
    ],
  },
  {
    id: 'musical-genres',
    name: 'Musical Genres',
    subject: 'Arts',
    description:
      'Let students vote on their favorite musical genres to explore music history and cultural influence.',
    topics: [
      'Rock',
      'Hip Hop',
      'Jazz',
      'Classical',
      'Pop',
      'Country',
      'R&B',
      'Electronic',
      'Reggae',
      'Blues',
      'Folk',
      'Metal',
      'Punk',
      'Gospel',
      'Soul',
      'Latin',
    ],
  },
  {
    id: 'world-wonders',
    name: 'World Wonders',
    subject: 'Geography',
    description:
      'Encourage students to research and debate which world landmark or wonder is the most impressive.',
    topics: [
      'Great Wall',
      'Machu Picchu',
      'Colosseum',
      'Taj Mahal',
      'Christ the Redeemer',
      'Chichen Itza',
      'Petra',
      'Great Pyramid',
      'Stonehenge',
      'Angkor Wat',
      'Eiffel Tower',
      'Statue of Liberty',
      'Parthenon',
      'Big Ben',
      'Golden Gate Bridge',
      'Sydney Opera House',
    ],
  },
  {
    id: 'superheroes',
    name: 'Superheroes',
    subject: 'Pop Culture',
    description:
      'Engage students with a fun bracket to determine the ultimate superhero through class votes.',
    topics: [
      'Spider-Man',
      'Batman',
      'Superman',
      'Wonder Woman',
      'Iron Man',
      'Captain America',
      'Black Panther',
      'Thor',
      'Wolverine',
      'The Flash',
      'Aquaman',
      'Hulk',
      'Deadpool',
      'Storm',
      'Supergirl',
      'Nightwing',
    ],
  },
  {
    id: 'mythological-creatures',
    name: 'Mythological Creatures',
    subject: 'Literature',
    description:
      'Use mythology to spark creative writing and debate about the most powerful mythological creature.',
    topics: [
      'Dragon',
      'Phoenix',
      'Unicorn',
      'Griffin',
      'Kraken',
      'Minotaur',
      'Cerberus',
      'Hydra',
      'Pegasus',
      'Sphinx',
      'Thunderbird',
      'Basilisk',
      'Chimera',
      'Werewolf',
      'Mermaid',
      'Centaur',
    ],
  },
  {
    id: 'this-or-that',
    name: 'This or That',
    subject: 'Fun',
    description:
      'A lighthearted icebreaker bracket where students vote on everyday preferences and debate their choices.',
    topics: [
      'Cats',
      'Dogs',
      'Pizza',
      'Tacos',
      'Summer',
      'Winter',
      'Mountains',
      'Beach',
      'Morning',
      'Night',
      'Books',
      'Movies',
      'City',
      'Countryside',
      'Sweet',
      'Savory',
    ],
  },
]
